language: java

jdk:
  - oraclejdk8
  
install: true 

before_script: .travis/set-version-if-tag.sh

script: mvn clean install

  
deploy:
  -
    on:
      tags: true
    provider: bintray
    skip_cleanup: true
    file: target/bintray.json
    user: goranstack
    key: $BINTRAY_API_KEY
    dry-run: true

cache:
  directories:
  - $HOME/.m2
