package com.bluebrim.base.shared;

import java.util.*;
/**
 * com.bluebrim.xmlstorage.impl.server.shared.Resource for country names in swedish, the call CoContryResources.getName("SE")
 * would give Sverige as result.
 */
public class CoCountryResources_sv extends CoCountryResources {
	private	static final Object[][] contents = {
		{"AF", "Afghanistan"},
		{"AL", "Albanien"},
		{"DZ", "Algeriet"},
		{"AD", "Andorra"},
		{"AO", "Angola"},
		{"AI", "Anguilla"},
		{"AQ", "Antarktis"},
		{"AG", "Antigua och Barbuda"},
		{"AR", "Argentina"},
		{"AM", "Armenien"},
		{"AW", "Aruba"},
		{"AU", "Australien"},
		{"AZ", "Azerbaijan"},
		{"BS", "Bahamas"},
		{"BH", "Bahrain"},
		{"BD", "Bangladesh"},
		{"BB", "Barbados"},
//		{"BY", "Belarus"},
		{"BE", "Belgien"},
		{"BZ", "Belize"},
		{"BJ", "Benin"},
		{"BM", "Bermuda"},
		{"BT", "Bhutan"},
		{"BO", "Bolivia"},
		{"BA", "Bosnien-Hercegovina"},
		{"BW", "Botsvana"},
		{"BV", "Bouvetön"},
		{"BR", "Brasilien"},
		{"IO", "Brittiska territoriet i Indiska oceanen"},
		{"BN", "Brunei Darussalam"},
		{"BG", "Bulgarien"},
		{"BF", "Burkina Faso"},
		{"BI", "Burundi"},
		{"CV", "Cap Verde"},
		{"KY", "Caymanöarna"},
		{"CF", "Centralafrikanska republiken"},
		{"CL", "Chile"},
		{"CO", "Colombia"},
		{"KM", "Comorerna"},
		{"CK", "Cooköarna"},
		{"CR", "Costa Rica"},
		{"CI", "Cote D'Ivoire"},
		{"CU", "Cuba"},
		{"CY", "Cypern"},
		{"DK", "Danmark"},
		{"CD", "Demokratiska republiken Kongo (fd Zaire)"},
		{"DJ", "Djibouti"},
		{"DM", "Dominika"},
		{"DO", "Dominikanska republiken"},
		{"EC", "Ecuador"},
		{"EG", "Egypten"},
		{"SV", "El Salvador"},
		{"ER", "Eritrea"},
		{"EE", "Estland"},
		{"ET", "Etiopien"},
		{"FK", "Falklandsöarna"},
		{"FJ", "Fiji"},
		{"PH", "Filippinerna"},
		{"FI", "Finland"},
		{"FR", "Frankrike"},
		{"GF", "Franska Guiana"},
		{"PF", "Franska Polynesien"},
//		{"PF", "Franska sydliga områdena"},
		{"FO", "Färöarna"},
		{"AE", "Förenade Arabemiraten"},
		{"GA", "Gabon"},
		{"GM", "Gambia"},
		{"GE", "Georgien"},
		{"GH", "Ghana"},
		{"GI", "Gibraltar"},
		{"GR", "Grekland"},
		{"GD", "Grenada"},
		{"GL", "Grönland"},
		{"GP", "Guadaloupe"},
		{"GU", "Guam"},
		{"GT", "Guatemala"},
		{"GN", "Guinea"},
		{"GW", "Guinea-Bissau"},
		{"GY", "Guyana"},
		{"HT", "Haiti"},
		{"HM", "Heardön o McDonaldsdön"},
//		{"NL", "Holland"},
		{"HN", "Honduras"},
		{"HK", "Hongkong"},
		{"IN", "Indien"},
		{"ID", "Indonesien"},
		{"IQ", "Irak"},
		{"IR", "Iran"},
		{"IE", "Irland"},
		{"IS", "Island"},
		{"IL", "Israel"},
		{"IT", "Italien"},
		{"JM", "Jamaica"},
		{"JP", "Japan"},
		{"YE", "Jemen"},
//		{"GB", "Jersey"},
		{"JO", "Jordanien"},
		{"YU", "Jugoslavien"},
		{"VG", "Jungfruöarna", "brittiska"},
		{"KH", "Kambodja"},
		{"CM", "Kamerun"},
//		{"KH", "Kampuchea"},
		{"CA", "Kanada"},
//		{"GB", "Kanalöarna"},
//		{"ES", "Kanarieöarna"},
		{"KZ", "Kazachstan"},
		{"KE", "Kenya"},
		{"CN", "Kina"},
		{"KG", "Kirgizistan"},
		{"KI", "Kiribati"},
		{"CG", "Kongo"},
		{"KP", "Korea (demokratisk folkrepublik)"},
//		{"KR", "Korea (republik)"},
//		{"FR", "Korsika"},
		{"HR", "Kroatien"},
		{"KW", "Kuwait"},
		{"LA", "Laos"},
		{"LS", "Lesotho"},
		{"LV", "Lettland"},
		{"LB", "Libanon"},
		{"LR", "Liberia"},
		{"LY", "Libyen"},
		{"LI", "Liechtenstein"},
		{"LT", "Litauen"},
		{"LU", "Luxemburg"},
		{"MO", "Macao"},
		{"MG", "Madagaskar"},
//		{"PT", "Madeira"},
		{"MK", "Makedonien"},
		{"MW", "Malawi"},
		{"MY", "Malaysia"},
		{"MV", "Maldiverna"},
		{"ML", "Mali"},
		{"MT", "Malta"},
//		{"FK", "Malvinas"},
		{"MA", "Marocko"},
		{"MH", "Marshallöarna"},
		{"MQ", "Martinique"},
		{"MR", "Mauretanien"},
		{"MU", "Mauritius"},
		{"YT", "Mayotte"},
		{"MX", "Mexico"},
		{"FM", "Mikronesien"},
		{"MZ", "Mocambique"},
		{"MD", "Moldavien"},
		{"MC", "Monaco"},
		{"MN", "Mongoliet"},
		{"MS", "Montserrat"},
		{"MM", "Myanmar"},
		{"NA", "Namibia"},
		{"NR", "Nauru"},
		{"NL", "Nederländerna"},
		{"AN", "Nederländska Antillerna"},
//		{"SR", "Nederländska Guiana"},
		{"NP", "Nepal"},
		{"NI", "Nicaragua"},
		{"NE", "Niger"},
		{"NG", "Nigeria"},
		{"NU", "Niue"},
		{"NF", "Norfolkön"},
		{"NO", "Norge"},
		{"MP", "Norra Marianerna"},
		{"NC", "Nya Caledonien"},
		{"NZ", "Nya Zeeland"},
		{"OM", "Oman"},
		{"PK", "Pakistan"},
		{"PW", "Palau"},
		{"PS", "Palestina"},
		{"PA", "Panama"},
		{"PG", "Papua Nya Guinea"},
		{"PY", "Paraguay"},
		{"PE", "Peru"},
		{"PN", "Pitcairn"},
		{"PL", "Polen"},
		{"PT", "Portugal"},
		{"PR", "Puerto Rico"},
		{"QA", "Qatar"},
		{"RE", "Réunion"},
		{"RO", "Rumänien"},
		{"RW", "Rwanda"},
		{"RU", "Ryssland"},
		{"SB", "Salomonöarna"},
		{"WS", "Samoa"},
		{"SM", "San Marino"},
		{"KN", "St Christopher och Nevis"},
		{"SH", "St Helena"},
		{"LC", "St Lucia"},
		{"PM", "St Pierre och Miquelon"},
		{"VC", "St Vincent och Grenadinerna"},
		{"ST", "Sao Tomé och Principe"},
		{"SA", "Saudi-Arabien"},
		{"CH", "Schweiz"},
		{"SN", "Senegal"},
		{"SC", "Seychellerna"},
		{"SL", "Sierra Leone"},
		{"SG", "Singapore"},
//		{"GB", "Skottland"},
		{"SK", "Slovakien"},
		{"SI", "Slovenien"},
		{"SO", "Somalia"},
		{"ES", "Spanien"},
//		{"NO", "Spetsbergen"},
		{"LK", "Sri Lanka"},
		{"GB", "Storbritannien"},
		{"SD", "Sudan"},
		{"SR", "Suriname"},
		{"SJ", "Svalbard och Jan Mayen"},
		{"SZ", "Swaziland"},
		{"SE", "Sverige"},
		{"ZA", "Sydafrika"},
		{"KR", "Sydkorea"},
		{"SY", "Syrien"},
		{"TJ", "Tadzjikistan"},
		{"TW", "Taiwan"},
		{"TZ", "Tanzania"},
		{"TD", "Tchad"},
		{"TH", "Thailand"},
		{"CZ", "Tjeckiska republiken"},
		{"TG", "Togo"},
		{"TO", "Tonga"},
		{"TT", "Trinidad och Tobago"},
		{"TK", "Tukelau"},
		{"TN", "Tunisien"},
		{"TR", "Turkiet"},
		{"TM", "Turkmenistan"},
		{"TC", "Turks- o Calcosöarna"},
		{"TV", "Tuvalu"},
		{"DE", "Tyskland"},
		{"UG", "Uganda"},
		{"UA", "Ukraina"},
		{"HU", "Ungern"},
		{"UY", "Uruguay"},
		{"US", "USA"},
		{"UZ", "Uzbekistan"},
		{"VU", "Vanuatu"},
		{"VA", "Vatikanstaten"},
		{"VE", "Venezuela"},
		{"VN", "Vietnam"},
//		{"VG", "Virgin Islands", "brittiska"},
		{"VI", "Virgin Islands", "amerikanska"},
		{"BY", "Vitryssland"},
		{"EH", "Västra Sahara"},
//		{"WS", "Västra Samoa"},
		{"WF", "Wallis o Futunaöarna"},
//		{"YE", "Yemen"},
		{"ZM", "Zambia"},
		{"ZW", "Zimbabwe"},
		{"ÅL", "Åland"},
		{"AT", "Österrike"},
		{"TP", "Östra Timor"},
	};
public Object[][] getContents() {
	return contents;
}
public static Map getReversedContents() {
	int size = contents.length;
	Map result = new HashMap(size);
	for (int i=0;i<size;i++)
	{
		Object element[] = contents[i];
		result.put(((String )element[1]).toUpperCase(), element[0]); 
	}
	return result;
}
}
