package com.bluebrim.gui.client;

import java.awt.*;

import javax.swing.*;
/**
 * Abstrakt klass som subklassas för att
 * köra ett CoUserInterface som applet.
 * <br>
 * Abstrakta metoder som måste implementeras i subklassen:
 * <ul>
 * <li>getUserInterface() - som svarar med en instans av den CoUserInterfaceklass
 * som skall visas upp.
 * </ul>
 * @author Lasse Svadängs 971008
 */
public abstract class CoUserInterfaceApplet extends JApplet {
/**
 */
public abstract void doInit();
/**
 * Information about this applet.
 */
public String getAppletInfo() {
	return "UserInterfaceApplet\n" + 
		"\n" + 
		"This applet was generated by a VisualAge SmartGuide.\n" + 
		"";
}
/**
 * Abstrakt metod som i subklassen skall svara med en instans
 * av det CoUserInterface jag skall visa upp. 
 */
public abstract CoUserInterface getUserInterface();
/**
 * Initializes the applet.
 * 
 */
public void init() {
	super.init();
	doInit();
	this.getContentPane().setLayout(new BorderLayout());
	CoUserInterface tUserInterface = getUserInterface();
	tUserInterface.buildForComponent();
	this.getContentPane().add(tUserInterface.getPanel());
}
/**
 * paint() draws the text on the drawing area.
 */
public void paint(Graphics g) {
	super.paint(g);
}
}
