package com.bluebrim.paint.impl.shared;
import java.io.*;

/**
 * This class was generated by a SmartGuide.
 * 
 */
public class CoColorSpace implements Serializable, Cloneable{
public Object clone() throws CloneNotSupportedException
{
	return (CoColorSpace )super.clone();
}
}
