package com.bluebrim.layoutmanager.test;

import java.awt.*;
import java.awt.event.*;

/**
 * Displays a message box to the user with an OK button on it
 * Can be used to display error messages to the user whenever
 * he enters invalid input
 * @author Murali Ravirala
 * @version 1.0
 */

class MessageBox extends Dialog {

  /**
   * An inner class that listens to the events generated by the message box
   * and performs action accordingly
   */

  class MessageBoxListener implements ActionListener {
	/**
	 * Disposes the message box
	 * @param e  the action event that indicates the action that was performed
	 */
	public void actionPerformed(ActionEvent e) {
		// disposes the current dialog box
		dispose();
	} // actionPerformed()
  } // MessageBoxListener
	/**
	 * Creates a new message box with the frame and displays the
	 * message on it along with an OK button it
	 */
	MessageBox(Frame frame, String message, boolean modal) {
		super(frame, "Error", modal);
		// display the label in the center
		Label label = new Label(message, Label.CENTER);
		add("Center", label);
		setResizable(false);
		setSize(300, 150);
		setLocation(320,240);
		Button b = new Button("OK");
		MessageBoxListener msglst = new MessageBoxListener();
		b.addActionListener(msglst);
		Panel p = new Panel();
		GridLayout gridlayout = new GridLayout(2, 3);
		p.setLayout(gridlayout);
		p.add(new Panel());
		p.add(b);
		p.add(new Panel());
		p.add(new Panel());
		p.add(new Panel());
		p.add(new Panel());
		add("South", p);
		addWindowListener(new Terminator(frame));
		show();
	} // Message()
} // MessageBox
